export const InputValues = [
  {
    id: 1,
    labelClassName: "sku",
    idName: "sku",
    name: "sku",
    type: "text",
    inputClassName: "form-control",
    label: "SKU:",
    errorMessage: "*Please provide SKU",
  },
  {
    id: 2,
    labelClassName: "name",
    idName: "name",
    name: "name",
    type: "text",
    inputClassName: "form-control",
    label: "Name:",
    errorMessage: "*Please provide Name",
  },
  {
    id: 3,
    labelClassName: "price",
    idName: "price",
    name: "price",
    type: "number",
    inputClassName: "form-control",
    step: ".01",
    label: "Price:",
    errorMessage: "*Please provide price (in numbers)",
  },
];

export const DimensionInputValues = [
  {
    id: 1,
    labelClassName: "height",
    idName: "height",
    name: "height",
    type: "number",
    inputClassName: "form-control",
    label: "Height (CM):",
    errorMessage: "*Please provide the data of indicated type",
  },
  {
    id: 2,
    labelClassName: "width",
    idName: "width",
    name: "width",
    type: "number",
    inputClassName: "form-control",
    label: "Width (CM):",
    errorMessage: "*Please provide the data of indicated type",
  },
  {
    id: 3,
    labelClassName: "length",
    idName: "length",
    name: "length",
    type: "number",
    inputClassName: "form-control",
    label: "Length (CM):",
    errorMessage: "*Please provide the data of indicated type",
  },
  {
    id: 4,
    labelClassName: "size",
    idName: "size",
    name: "size",
    type: "number",
    inputClassName: "form-control",
    label: "Size (CM):",
    errorMessage: "*Please provide the data of indicated type",
  },
  {
    id: 5,
    labelClassName: "weight",
    idName: "weight",
    name: "weight",
    type: "number",
    inputClassName: "form-control",
    label: "Weight (CM):",
    errorMessage: "*Please provide the data of indicated type",
  },
];
